name: Test alpine

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:${{ matrix.node }}-alpine
    strategy:
      fail-fast: false
      matrix:
        node:
          - 14
          - 16
          - 18

    steps:
      - name: Install Alpine build tools
        run: apk add --no-cache python3 make git gcc g++

      - uses: actions/checkout@v3

      - name: Install packages
        run: npm install --unsafe-perm

      - name: Run tests
        run: npm test
